version: '2'

services:
    user-db:
        build:
            context: ./docker/user-db/
        image: mongo:3.0.4
        hostname: user-db
        restart: always
        #volumes:
          #- ./database:/data
        environment:
            - reschedule=on-node-failure  
        
        ports:
            - "27017:27017"
        
    user:
        build:
            context: .
        image: arijmansour/pfe_user_microservice:latest
        #depends_on:
         #user-db:
           #condition: service_healthy
        hostname: pfe_user_microservice
        restart: always
        cap_drop:
            - all
        cap_add:
            - NET_BIND_SERVICE
        read_only: true
        environment:
            - MONGO_HOST=user-db:27017
            - reschedule=on-node-failure
        ports:
            - "8080:80"
    
